#!/usr/bin/env bash

#set colors generated by 'wal'
#. "${HOME}/.cache/wal/colors.sh"

 reload_dunst() {
    pkill dunst
    dunst \
	-frame_width 0 \
        -lb "#282a36" \
        -nb "#282a36" \
        -cb "#50fa7b" \
        -bf "#ff79c6" \
        -cf "#bd93f9" \
        -nf "#ffffff" &
}

reload_dunst
