#!/bin/bash
BATTERY=(          )
PC=$(acpi | awk '{print $4}' | tr -d '%,0')
INDEX=$(echo "$PC/10" | bc)
STATUS=$(acpi | awk '{print $3}' | tr -d ',')
if [[ $STATUS = "Charging" ]]; then
    INDEX=$(echo $(date +%s) % 9 | bc)
    C=""
    echo $PC"% "${BATTERY[$INDEX]}" "${C}
    exit
fi
echo $PC"% "${BATTERY[$INDEX]}
